apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret
spec:
 containers:
   - name: secret-cont
     image: busybox
     command: ["/bin/sh"]
     args: ["-c", "sleep 600"]
     env: 
       - name: USR
         valueFrom:
           secretKeyRef:
             name: secret-sample
             key: username
       - name: PWD
         valueFrom:
            secretKeyRef:
              name: secret-sample
              key: password
      

