apiVersion: v1
kind: Pod
metadata:
   name: config-sample-env
spec:
   containers:
       - name: config-cont
         image: busybox
         command: ["/bin/sh"]
         args: ["-c", "sleep 600"]
         env:
           - name: SCRIPT
             valueFrom:
                configMapKeyRef:
                   name: configmap-sample
                   key: user.role
           - name: LEAD
             valueFrom:
                configMapKeyRef:
                   name: configmap-sample
                   key: user.name           


